services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: my-backend:latest
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=${OLLAMA_URL:-http://ollama:11434}
    depends_on:
      - ollama
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./models:/models
      - ./entrypoint.sh:/entrypoint.sh
    restart: unless-stopped
    entrypoint: ["/bin/bash", "/entrypoint.sh"]

volumes:
  - ./chroma_db:/chroma_db
  - ./models:/models
