services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: my-backend:latest
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    restart: unless-stopped
