name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint-test:
    name: 🧪 Run Pre-Commit, Linting & Tests
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout Repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: 📦 Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt
          pip install pre-commit mypy pytest requests types-requests

      - name: 🔎 Run Pre-Commit Hooks
        run: pre-commit run --all-files

      - name: 📏 Run Mypy Type Checking
        run: mypy backend

      - name: 🛡️ Run Security Checks (Bandit)
        run: bandit -r backend

      - name: ✅ Run Tests
        run: pytest --disable-warnings
